### ISSUE TITLE
Application as a contributor to the script library and tutorial pages

### ISSUE THREAD

**Issue by Timmeey86** [open-modding-alliance/.github#1]
Hi there. As someone who struggled quite a long time with figuring out how to script for Farming Simulator in the past, I'd like to join your group in order help give others more of a head start.

Your nickname: Farmsim Tim (old accounts like discord/github will be called Timmeey86)
Do you have mod published on official ModHub: yes
https://www.farming-simulator.com/mods.php?lang=en&country=gb&title=fs2022&filter=org&org_id=232374&page=0#
They're also all on Git Hub, usually with an MIT License and annotated (though not fully, as I've learnt recently)

**Main Skills [yes/no]**
LUA/scripting: yes
3D Modelling: no
In-game XML: yes
Textures/2D graphics: no
Python: yes

**Additional skills relevant for FS Modding (e.g. Maya/Houdini/Blender, shaders):**
I've started writing a script modding wiki which I plan to update for FS25 and only now discovered OMA. I guess it would make sense to integrate the tutorial into OMA instead of continuing it as a separate wiki: https://github.com/Timmeey86/fs22-script-modding-tutorial/wiki

**Comment by w33zl** [comment]
Hi, Your skills and mindset sounds like a great fit, welcome!
